### ISSUE TITLE
feat(cli): query commands

### ISSUE THREAD

**Issue by merklefruit** [chainbound/mevboost-relay-api#1]
Write the basic CLI module to be able to call the library functions from the terminal.

Example usage:

```shell
# fetch and output data to CSV (or to stdout if flag --csv is not specified)
mevboost-relay-api query validators-current-and-next-epoch --csv
```

```[tasklist]
### Tasks
- [ ] get_validators_for_current_and_next_epoch
- [ ] get_validator_registration_on_all_relays
- [ ] get_validator_registration
- [ ] get_validator_registration_for_all_slots_on_all_relays
```

**Comment by quangkeu95** [comment]
happy to help!
